// authActionTypes
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const LOGOUT = "LOGOUT";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

// lockerActionTypes
export const FETCH_LOCKERS_SUCCESS = "FETCH_LOCKERS_SUCCESS";
export const FETCH_LOCKERS_FAIL = "FETCH_LOCKERS_FAIL";
export const CREATE_LOCKER_SUCCESS = "CREATE_LOCKER_SUCCESS";
export const CREATE_LOCKER_FAIL = "CREATE_LOCKER_FAIL";
export const DELETE_LOCKER_SUCCESS = "DELETE_LOCKER_SUCCESS";
export const DELETE_LOCKER_FAIL = "DELETE_LOCKER_FAIL";
// types.js
export const GET_LOCKERS = "GET_LOCKERS";
export const LOCKER_ERROR = "LOCKER_ERROR";
export const ADD_LOCKER = "ADD_LOCKER";
export const UPDATE_LOCKER_STATUS = "UPDATE_LOCKER_STATUS";
export const DELETE_LOCKER = "DELETE_LOCKER";

// Add other action types as needed

// bookingActionTypes
export const FETCH_BOOKINGS_SUCCESS = "FETCH_BOOKINGS_SUCCESS";
export const FETCH_BOOKINGS_FAIL = "FETCH_BOOKINGS_FAIL";
export const CREATE_BOOKING_SUCCESS = "CREATE_BOOKING_SUCCESS";
export const CREATE_BOOKING_FAIL = "CREATE_BOOKING_FAIL";
export const DELETE_BOOKING_SUCCESS = "DELETE_BOOKING_SUCCESS";
export const DELETE_BOOKING_FAIL = "DELETE_BOOKING_FAIL";
export const GET_BOOKINGS = "CREATE_BOOKING_FAIL";
export const BOOKING_ERROR = "DELETE_BOOKING_SUCCESS";
export const ADD_BOOKING = "DELETE_BOOKING_FAIL";
export const UPDATE_BOOKING_STATUS = "UPDATE_BOOKING_STATUS";
export const DELETE_BOOKING = "DELETE_BOOKING";

// dashboardActionTypes
export const FETCH_DASHBOARD_SUCCESS = "FETCH_DASHBOARD_SUCCESS";
export const FETCH_DASHBOARD_FAIL = "FETCH_DASHBOARD_FAIL";
export const GET_ADMIN_DASHBOARD = "GET_ADMIN_DASHBOARD";
export const DASHBOARD_ERROR = "DASHBOARD_ERROR";
export const GET_USER_DASHBOARD = "GET_USER_DASHBOARD";

// reportActionTypes
export const FETCH_REPORTS_SUCCESS = "FETCH_REPORTS_SUCCESS";
export const FETCH_REPORTS_FAIL = "FETCH_REPORTS_FAIL";
